const assert = require('node:assert/strict');
const fs = require('node:fs');
const { execFileSync } = require('node:child_process');
const path = require('node:path');

const root = path.join(__dirname, '..');
execFileSync(process.execPath, ['build.js'], { cwd: root, stdio: 'pipe' });
const html = fs.readFileSync(path.join(root, 'dist', 'tile-calculator.html'), 'utf8');

assert.match(html, /<title>Tile Overage Calculator — How Many Tiles Do I Need\? \(Boxes & Square Feet\)<\/title>/);
assert.match(html, /<meta name="description" content="Tile overage calculator for floors, walls, bathrooms, and showers\. Calculate tiles, square feet, whole boxes, and 10%, 15%, or 20% extra for cuts and breakage\.">/);
assert.match(html, /id="coverage"/);
assert.match(html, /Box coverage/);
assert.match(html, /Math\.ceil\(area\*\(1\+waste\/100\)\/coverage\)/);
assert.match(html, /Enter the square-foot coverage printed on the box/);
assert.match(html, /Compare the calculator's tile count with the coverage printed on the box/);
assert.match(html, /If the package coverage differs from the nominal tile size, use the package coverage to make the purchase decision/);
assert.match(html, /Buy all visible-field tile from the same dye lot when possible/);
assert.match(html, /Measure doorways, floor vents, and built-in cabinets separately before subtracting them from the field area/);
assert.match(html, /Buy each product as a separate order because floor, wall, trim, and mosaic boxes can have different coverage and dye lots/);
assert.match(html, /Dry-lay a few rows and plan the cuts at opposite walls before opening every box/);
assert.match(html, /How much extra tile should I keep for future repairs\?/);
assert.match(html, /Keep at least one unopened box when the budget and storage allow/);
assert.match(html, /How much tile overage do I need\?/);
assert.match(html, /Use 10% for a rectangular field with a straight layout, 15% when the room has many cuts or the layout is offset, and 20% for diagonal or herringbone patterns/);
assert.match(html, /A 120 sq ft bathroom at 15% needs 138 sq ft of tile before box rounding/);
assert.match(html, /Does tile overage include box rounding\?/);
assert.match(html, /If a 100 sq ft floor needs 110 sq ft after a 10% allowance and each box covers 12\.5 sq ft, round 8\.8 boxes up to 9/);
assert.match(html, /href="\/thinset-calculator"/);
assert.match(html, /href="\/grout-calculator"/);
assert.match(html, /<link rel="canonical" href="https:\/\/calculapedia\.com\/tile-calculator">/);
const schema = JSON.parse(html.match(/<script type="application\/ld\+json">\s*([\s\S]*?)\s*<\/script>/)[1]);
assert.equal(schema['@context'], 'https://schema.org');
assert.ok(schema['@graph'].some(item => item['@type'] === 'FAQPage'));
console.log('tile content, metadata, canonical, internal links, and FAQ schema verified');
